spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empbenefit
    username: root
    password: root
server:
  port: 8080
  servlet:
    contextPath: /demo1